version: 0.2

phases:
  build:
    commands:
      - echo Starting the build phase..
      - java -version
      - mvn clean install package
  post_build:
    commands: 
      - echo Successfully completed build phase
      - mv target/aws-elasticbeanstalk-example-1-0.0.1-SNAPSHOT.war ./ROOT.war
      - ls -ltr
artifacts:
  files:
    - ./ROOT.war